Add sign, verify and read key models.
Chatham/Vault.NET pull request #6
Opened 2018-01-18 08:46 UTC by LensArt

We use some other parts of vault so we added the model to be able to use these. For reference: https://www.vaultproject.io/api/secret/transit/index.html

2018-01-19 21:01 UTC, grounded042 commented
Thanks for the PR @LensArt. I've got a couple of comments / questions, but this is looking real nice.

2018-01-19 22:22 UTC, grounded042 requested changes
Thanks again for the PR. I have a couple of things mentioned and then we should be good to merge.

2018-01-19 22:22 UTC, grounded042 commented on src/Vault/Models/Secret/Transit/ReadKeyResponse.cs
> +}
Are you missing the `latest_version`, `backup_info`, and `restore_info` fields?

2018-01-19 22:22 UTC, grounded042 commented on src/Vault/Models/Secret/Transit/SignRequest.cs
> +}
Are you missing the `ker_version` field?

2018-01-19 22:22 UTC, grounded042 commented on src/Vault/Models/Secret/Transit/SignResponse.cs
> +}
I think this could also have a `public_key` field.

2018-01-19 22:22 UTC, grounded042 commented on src/Vault/Vault.csproj
> +    <PackageVersion>0.9.2.0</PackageVersion>
We mirror the Vault version and only create new point releases for PRs and such that are not lined up with a newer version of Vault. Could you move this to `0.9.1.1`?

2018-01-29 14:54 UTC, LensArt commented
Thanks for the feedback, I first based the models on the response examples in the API documentation. I have now updated the models according to your suggestions and looking into the Vault code. This should cover all possible properties.

2018-01-29 21:06 UTC, grounded042 approved these changes

2018-01-29 21:06 UTC, grounded042 commented
Looks good. Thanks for the contribution @LensArt!

2018-01-29 21:06 UTC, merged